language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - pip install codecov
    - pip install requirements.txt
    - python setup.py build_ext --inplace
script:
    - coverage run tests.py
after_success:
    - codecov
